[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "interfaces/L2/=lib/optimism/packages/contracts-bedrock/interfaces/L2/",
    "interfaces/IGasTank.sol=interfaces/IGasTank.sol",
    "src/libraries/=lib/optimism/packages/contracts-bedrock/src/libraries/",
    "src/universal/=lib/optimism/packages/contracts-bedrock/src/universal/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
