[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "optimism/interfaces/=lib/optimism/packages/contracts-bedrock/interfaces/",
    "optimism/src/libraries/=lib/optimism/packages/contracts-bedrock/src/libraries/",
    "optimism/src/universal/=lib/optimism/packages/contracts-bedrock/src/universal/"
]
fs_permissions = [
  { access='read-write', path='./' },
]

